### ISSUE TITLE
Secondary devices not connecting

### ISSUE THREAD

**Issue by baxtmi** [twocolors/node-red-contrib-midea-hvac#11]
Hi,

I recently migrated my devices over from the midea air app to the msmarthome app. I then updated to v1.2.3 of your node and went about loading my 3 AC units into the new version using my migrated account. The first AC integrates fine using the OSK103 method. I then create a new hvac-config setup on a new block and constantly get a "failed to communicate" error.  How do I resolve this please?

**Comment by baxtmi** [comment]
Hi, My apologies, I typed the wrong thing. I meant to say that it "Failed to authenticate". But to answer your question, I can see the new devices and I can select them, but as soon as I have one block running, all the other blocks give the error

**Comment by twocolors** [comment]
I think I know what is the bug, please show me "discovery"

How show discovery - https://github.com/reneklootwijk/node-mideahvac#discovery

**Comment by twocolors** [comment]
I found where the bug is, I will fix it soon

**Comment by baxtmi** [comment]
I'm afraid I'm not sure how to run that code? I'm running this on a
raspberry pi, and I did the install via the palette editor, and then I
modify the nodes via a browser from another machine. I'm not familiar with
accessing the files via a command line.

**Comment by baxtmi** [comment]
> I found where the bug is, I will fix it soon

Thanks very much

**Comment by twocolors** [comment]
try node-red-contrib-midea-hvac@1.2.4
