### ISSUE TITLE
No Midea HVAC Devices Found

### ISSUE THREAD

**Issue by chasehobbs** [twocolors/node-red-contrib-midea-hvac#12]
I am trying to setup this node but cannot seem to get the connection working. I have migrated my account and devices to the MSmartHome app but whenever I hit the discover button I get the error "No Midea HVAC Devices Found". I'm honestly not sure how to tell if my Midea AC uses the OSK103/SK103 dongle. My model is MAP14HS1TBL. I've also tried pre-filling in the IP address but that still does not help.

**Comment by twocolors** [comment]
hi in AC you will see dongle like [more info](https://github.com/reneklootwijk/node-mideahvac/issues/14)

![photo_2022-09-19_11-15-59](https://user-images.githubusercontent.com/207796/190976530-8fa85707-44d7-4a7b-a49b-9e53881e63f8.jpg)
![photo_2022-09-19_11-15-16](https://user-images.githubusercontent.com/207796/190976532-784a8477-97a9-48e9-bcde-f292601ab9c5.jpg)
![photo_2022-09-19_11-17-21](https://user-images.githubusercontent.com/207796/190976537-14c1e39a-52de-483f-adcd-19002c09a06f.jpg)
![photo_2022-09-19_11-16-57](https://user-images.githubusercontent.com/207796/190976539-5a833bcd-8ca2-4904-b5ee-7de951e8e274.jpg)

support only this

**Comment by dkomljenovic2502** [comment]
hi, 
was this solved and i don't see it or moved to will not fix?

BR,
Darko

**Comment by chasehobbs** [comment]
It is not solved, I'm hesitant to disassemble the unit to look for the wifi dongle. I'm still unable to find the device using this plugin.

**Comment by twocolors** [comment]
this plugin only supports 103 keys, if you want to work you can't use

https://aliexpress.com/item/32815395082.html + [esp-link](https://github.com/jeelabs/esp-link/releases/tag/V3.0.14) more info [ADAPTER.md](https://github.com/reneklootwijk/node-mideahvac/blob/master/ADAPTER.md)

**Comment by chasehobbs** [comment]
I'm curious if we could look at this as feature request to explore using the OEM key provided on these newer devices. It would lower the barrier to entry instead of asking users to tear open an $800 AC and install a wireless key from Ali Express.

**Comment by twocolors** [comment]
**do not open!!!**

oh, you have a portable / floor standing air conditioner. Most models that can be controlled are listed https://community.home-assistant.io/t/midea-a-c-and-esphome-component-list-of-all-known-working-models-and-manufacturers/320784

in general, my node is a binding for the @reneklootwijk solution, maybe he will tell you
