### ISSUE TITLE
Failed to authenticate

### ISSUE THREAD

**Issue by slima** [twocolors/node-red-contrib-midea-hvac#14]
Hello, I discovered hvac but I got Failed to authenticate.

ID, key and token got retrived from account.

**Comment by twocolors** [comment]
use MSmartHome account ?

**Comment by slima** [comment]
Yes, account migrated to MSmartHome from Midea Air app.

**Comment by twocolors** [comment]
dongle 103 or 105 ?

**Comment by slima** [comment]
Hi, 105

**Comment by twocolors** [comment]
more https://github.com/twocolors/node-red-contrib-midea-hvac/issues/12
