### ISSUE TITLE
Comfee Luftentfeuchter, 20 L/24 h, Raumgröße ca.100 m³(40 m²), MDDF-20DEN7-WF, APP-fähig

### ISSUE THREAD

**Issue by hannoverRed** [twocolors/node-red-contrib-midea-hvac#2]
Hallo,

könnte man die Unterstützung zu dem `Comfee Luftentfeuchter, 20 L/24 h, Raumgröße ca.100 m³(40 m²), MDDF-20DEN7-WF, APP-fähig` bekommen?
[https://www.amazon.de/gp/product/B07MSL8YN7/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1](url)
er wird mir in red matic zwar als Gerät angezeigt, es kommt aber immer folgender Fehler
`Midea: Command wrong or device (xxxxxxxxxxxxxxxx) not reachable`  xxxx steht die Gerätenummer drinnen

`

Hersteller | Comfee
-- | --
MDDF-20DEN7-WF
35 x 24.5 x 51 cm; 15.1 Kilogramm
MDDF-20DEN7-WF
20L-40m²-DEN7-WF

`

Hier gefunden für Homeassistant
[https://www.techlover.de/2020/11/01/lufentfeuchter-comfee-in-home-assistant-und-homekit/]()

lg Jörn

**Comment by twocolors** [comment]
Ich werde versuchen, ein Modell für die Unterstützung zu finden

**Comment by hannoverRed** [comment]
Vielen Dank!

Falls sie fragen haben oder ich was testen soll bitte einfach Bescheid geben.
Lg

**Comment by hannoverRed** [comment]
Hallo, gibt es hier schon was neues?

**Comment by twocolors** [comment]
Noch nicht, bitte machen Sie einen Screenshot in node-red, wie es aussieht

**Comment by hannoverRed** [comment]
gerne,

<img width="816" alt="Bildschirmfoto 2021-01-02 um 16 25 56" src="https://user-images.githubusercontent.com/60238337/103460555-65a79480-4d17-11eb-99b5-033c29255f2c.png">

**Comment by twocolors** [comment]
@sittisal there is no way to add support to node-red
https://github.com/ttimpe/homebridge-midea/pull/29
?

thx

**Comment by hannoverRed** [comment]
gibt es hier eine Lösung?

**Comment by helloworld1987** [comment]
I am also not able to create a valid command...

**Comment by twocolors** [comment]
Sorry, I don't have a humidifier and didn't find one for the test. This module will only support AC.

**Comment by twocolors** [comment]
@helloworld1987 @hannoverRed you can try https://github.com/Hypfer/esp8266-midea-dehumidifier
