### ISSUE TITLE
Status query error

### ISSUE THREAD

**Issue by ZoleeBB** [twocolors/node-red-contrib-midea-hvac#5]
Hello!
I use it: node-red-contrib-midea-hvac (1.1.3)
Node - Red version: 0.20.8

My problem is that I want to query the status, the machine turns off.
To query status, I send an empty JSON string.
I tried to send a timestamp, but then I got an error: "Error getting status (An internal error occurred)"
When I send an empty JSON string using "inject node", I get back the status, but the device turns off.
Please help me to solve the problem.
Thank you very much!

**Comment by twocolors** [comment]
model ac?

**Comment by ZoleeBB** [comment]
Hello!
AC indoor: MA-12NXD0-I
WiFi stick: OSK103

**Comment by twocolors** [comment]
nodejs version ? can you update node-red ?

use media cloud is try use big BUG, cloud or not answer or not try value ...
mb modifi you AC to https://github.com/reneklootwijk/node-mideahvac/blob/master/ADAPTER.md

**Comment by ZoleeBB** [comment]
Hello!

I updated NodeRED. Now the version is: 1.3.2.
I use mide cloud. The problem remains.
I want to avoid using a modified WiFi key unless there is no other option.

**Comment by twocolors** [comment]
hi try 1.2.0 now support OSK103
