### ISSUE TITLE
Not able to reconnect after rebooting esp-link

### ISSUE THREAD

**Issue by antychrust** [twocolors/node-red-contrib-midea-hvac#6]
Hi,
I have an issue - when I reboot tha AC or unplug and plug again my ESP-12F stick to AC, then I need to completely restart node-red to make it work again. Node says "Error set status (No response received)".

**Comment by twocolors** [comment]
HI, try use 1.1.4

**Comment by antychrust** [comment]
Unfortunately it didn't help :(

**Comment by twocolors** [comment]
oh, could you write how to repeat this error step by step, so that I would repeat it at myself
