### ISSUE TITLE
Error getting status (An internal error occurred)

### ISSUE THREAD

**Issue by grahamrobertslx** [twocolors/node-red-contrib-midea-hvac#7]
This node was working fine for a while then has stopped. I get the error "Error getting status (An internal error occurred)" when injecting a time stamp.

if i move the node in the lay out and re-deploy it it comes back to life.

**Comment by twocolors** [comment]
use cloud or adapter ?

**Comment by grahamrobertslx** [comment]
It was using Cloud. I've not been able to get serial working yet.

**Comment by twocolors** [comment]
full deploy or "Modified Nodes" ?

**Comment by grahamrobertslx** [comment]
Both

**Comment by twocolors** [comment]
try node-red-contrib-midea-hvac@1.1.5 , if this error reply 5 times will be re-initialize new token

**Comment by milanissimo1989** [comment]
hey is Comfee MDDF-16DEN7-WF Luftentfeuchter working with this?

i get alltime the Message ""Error getting status (An internal error occurred)" if i inject timestamp!

![image](https://user-images.githubusercontent.com/87724241/147554043-0930ade7-3ef7-4cae-b66e-8d0dbb4ae105.png)

**Comment by hannoverRed** [comment]
no

**Comment by milanissimo1989** [comment]
Would there be one way to insert it?

**Comment by msmthng** [comment]
I have the same issue Error getting status (An internal error occurred) using 1.1.9 - any suggestions to debug this?

thx for support

**Comment by twocolors** [comment]
hi try 1.2.0 now support OSK103
