### ISSUE TITLE
Failed to retrieve devices An unknown error occurred

### ISSUE THREAD

**Issue by dhanzseros** [twocolors/node-red-contrib-midea-hvac#9]
Hey,

Previously this plugin worked for me in node-red but now it says after I input the account details: "Failed to retrieve devices An unknown error occurred". And the device does not show up in the settings of node.

Could you help in this?
Thanks,
David

**Comment by twocolors** [comment]
hi, i recommend to wait a bit for latest support https://github.com/reneklootwijk/node-mideahvac

But tonight I will release a patch for this error

**Comment by dhanzseros** [comment]
Hey,

thank you for your support! One of my friend using this AC. I had to migrate the device yesterday to another mobile application named MSmartHome because the older one showed up the support ends soon, you have to use this "new" app.

Maybe this also causes new problems with the connection. After the migrating he could not use his account to login the older ios app.

**Comment by twocolors** [comment]
hi try 1.2.0
